# OpenCodeBlock an open-source tool for modular visual programing in python
# Copyright (C) 2021 Mathïs FEDERICO <https://www.gnu.org/licenses/>

name: Python coverage

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-tk python3-dev
        sudo apt-get install xvfb
        sudo apt-get install --reinstall libxcb-icccm4
        sudo apt-get install --reinstall libxcb-image0
        sudo apt-get install --reinstall libxcb-keysyms1
        sudo apt-get install --reinstall libxcb-render-util0
        sudo apt-get install --reinstall libxcb-xkb1
        sudo apt-get install --reinstall libxkbcommon-x11-0
        sudo python -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        sudo pip install -r requirements-dev.txt

    - name: Build unit coverage using pytest-cov
      run: |
        sudo pytest --cov=opencodeblocks --cov-report=xml tests/unit
        sudo score=$(python coverage_score.py --score)
        sudo color=$(python coverage_score.py --color)
        sudo echo "COVERAGE_UNIT_SCORE=$score"
        sudo echo "COVERAGE_UNIT_COLOR=$color"
        sudo echo "COVERAGE_UNIT_SCORE=$score" >> $GITHUB_ENV
        sudo echo "COVERAGE_UNIT_COLOR=$color" >> $GITHUB_ENV
    - name: Create unit coverage badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 00ce73155619a4544884ca6d251954b3
        filename: opencodeblocks_unit_coverage_badge.json
        label: Unit coverage
        message: ${{ env.COVERAGE_UNIT_SCORE }}
        color: ${{ env.COVERAGE_UNIT_COLOR }}
        style: plastic
    - name: Build integration coverage using pytest-cov
      run: |
        sudo xvfb-run -n 55 pytest --cov=opencodeblocks --cov-report=xml tests/integration
        sudo score=$(xvfb-run python coverage_score.py --score)
        sudo color=$(xvfb-run python coverage_score.py --color)
        sudo echo "COVERAGE_INTEGRATION_SCORE=$score"
        sudo echo "COVERAGE_INTEGRATION_COLOR=$color"
        sudo echo "COVERAGE_INTEGRATION_SCORE=$score" >> $GITHUB_ENV
        sudo echo "COVERAGE_INTEGRATION_COLOR=$color" >> $GITHUB_ENV
      env:
        DISPLAY: :55
        QT_DEBUG_PLUGINS: 1
    - name: Create integration coverage badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 00ce73155619a4544884ca6d251954b3
        filename: opencodeblocks_integration_coverage_badge.json
        label: Integration coverage
        message: ${{ env.COVERAGE_INTEGRATION_SCORE }}
        color: ${{ env.COVERAGE_INTEGRATION_COLOR }}
        style: plastic